# Generated by Django 5.0.6 on 2024-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[(1, 'fruits'), (2, 'vegetables'), (3, 'fruit juice'), (4, 'fruit salad'), (5, 'vegetable juice'), (6, 'vegetable salad')], max_length=20),
        ),
    ]
