# Generated by Django 5.0.6 on 2024-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='full_description',
            field=models.TextField(default='txt'),
        ),
    ]
