# Generated by Django 5.0.6 on 2024-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_category_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/fruitica.png', null=True, upload_to='products/images'),
        ),
    ]
