# Generated by Django 5.0.6 on 2024-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('fruits', 'fruits'), ('vegetables', 'vegetables'), ('Fruit Juice', 'fruit juice'), ('Fruit Salad', 'fruit salad'), ('Vegetable juice', 'vegetable juice'), ('Vegetable Salad', 'vegetable salad'), ('other', 'other')], max_length=20),
        ),
    ]
