# Generated by Django 5.0.6 on 2024-05-22 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='date',
            new_name='Date_of_Expiry',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='full_description',
            new_name='Detailed_description',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='Date_of_manufacturing',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Dozen', 'Dozen'), ('liter', 'liter'), ('Nos', 'Nos'), ('Kg', 'kg')], default='Kg', max_length=30),
        ),
    ]
