# Generated by Django 5.0.6 on 2024-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_date_productdetails_date_of_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('liter', 'liter'), ('Dozen', 'Dozen'), ('Nos', 'Nos'), ('Kg', 'kg')], default='Kg', max_length=30),
        ),
    ]
