# Generated by Django 5.0.6 on 2024-05-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bannerpage_alter_productdetails_unit_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='ItemStatus',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='cartItemsQuantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('liter', 'liter'), ('Nos', 'Nos'), ('ml', 'ml'), ('Kg', 'kg'), ('Dozen', 'Dozen')], default='Kg', max_length=30),
        ),
    ]
