# Generated by Django 5.0.6 on 2024-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Kg', 'kg'), ('liter', 'liter'), ('ml', 'ml'), ('Dozen', 'Dozen'), ('Nos', 'Nos')], default='Kg', max_length=30),
        ),
    ]
