# Generated by Django 5.0.6 on 2024-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productdetails_unit_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Dozen', 'Dozen'), ('Nos', 'Nos'), ('gram', 'gram'), ('ml', 'ml'), ('Kg', 'kg'), ('liter', 'liter')], default='Kg', max_length=30),
        ),
    ]
