# Generated by Django 5.0.6 on 2024-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cart_user_alter_productdetails_unit_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='Date_of_Expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Dozen', 'Dozen'), ('gram', 'gram'), ('Nos', 'Nos'), ('Kg', 'kg'), ('liter', 'liter'), ('ml', 'ml')], default='Kg', max_length=30),
        ),
    ]
