# Generated by Django 5.0.6 on 2024-05-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Nos', 'Nos'), ('liter', 'liter'), ('gram', 'gram'), ('Dozen', 'Dozen'), ('ml', 'ml'), ('Kg', 'kg')], default='Kg', max_length=30),
        ),
    ]
