# Generated by Django 5.0.6 on 2024-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order_product_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Kg', 'kg'), ('liter', 'liter'), ('Nos', 'Nos'), ('Dozen', 'Dozen'), ('ml', 'ml'), ('gram', 'gram')], default='Kg', max_length=30),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
