# Generated by Django 5.0.6 on 2024-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'kg'), ('Dozen', 'Dozen'), ('gram', 'gram'), ('ml', 'ml'), ('Nos', 'Nos')], default='Kg', max_length=30),
        ),
    ]
