# Generated by Django 5.0.6 on 2024-06-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productdetails_unit_parameter_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('ml', 'ml'), ('Kg', 'kg'), ('Dozen', 'Dozen'), ('liter', 'liter'), ('gram', 'gram'), ('Nos', 'Nos')], default='Kg', max_length=30),
        ),
    ]
