# Generated by Django 5.0.6 on 2024-06-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_checkoutaddress_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='checkoutAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Checkout_addresses', to='products.checkoutaddress'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Nos', 'Nos'), ('liter', 'liter'), ('Dozen', 'Dozen'), ('gram', 'gram'), ('ml', 'ml'), ('Kg', 'kg')], default='Kg', max_length=30),
        ),
    ]
