# Generated by Django 5.0.6 on 2024-06-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_checkoutaddress_order_order_checkoutaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('gram', 'gram'), ('Dozen', 'Dozen'), ('ml', 'ml'), ('Nos', 'Nos'), ('liter', 'liter'), ('Kg', 'kg')], default='Kg', max_length=30),
        ),
    ]
