# Generated by Django 5.0.6 on 2024-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_productdetails_unit_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Kg', 'kg'), ('gram', 'gram'), ('ml', 'ml'), ('Nos', 'Nos'), ('liter', 'liter'), ('Dozen', 'Dozen')], default='Kg', max_length=30),
        ),
    ]
