# Generated by Django 5.0.6 on 2024-06-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_cartitems_is_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('ml', 'ml'), ('Dozen', 'Dozen'), ('Kg', 'kg'), ('gram', 'gram'), ('Nos', 'Nos'), ('liter', 'liter')], default='Kg', max_length=30),
        ),
    ]
