# Generated by Django 5.0.6 on 2024-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('liter', 'liter'), ('ml', 'ml'), ('Nos', 'Nos'), ('gram', 'gram'), ('Kg', 'kg'), ('Dozen', 'Dozen')], default='Kg', max_length=30),
        ),
    ]
