# Generated by Django 5.0.6 on 2024-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productdetails_unit_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Dozen', 'Dozen'), ('Nos', 'Nos'), ('ml', 'ml'), ('Kg', 'kg'), ('liter', 'liter'), ('gram', 'gram')], default='Kg', max_length=30),
        ),
    ]
