# Generated by Django 5.0.6 on 2024-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productdetails_unit_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit_parameter',
            field=models.CharField(choices=[('Kg', 'kg'), ('gram', 'gram'), ('Dozen', 'Dozen'), ('liter', 'liter'), ('Nos', 'Nos'), ('ml', 'ml')], default='Kg', max_length=30),
        ),
    ]
