# Generated by Django 5.0.6 on 2024-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
