# Generated by Django 5.0.6 on 2024-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpage',
            name='short_desc',
            field=models.TextField(),
        ),
    ]
