# Generated by Django 5.0.6 on 2024-06-04 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logintime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
